

import java.awt.BorderLayout;
import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import java.awt.Color;
import java.awt.Container;
import java.awt.Desktop;
import javax.swing.UIManager;
import java.awt.SystemColor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import java.awt.Font;
import java.awt.Image;
import java.awt.TextArea;
import javax.swing.JTextArea;
import javax.swing.border.LineBorder;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class comp extends javax.swing.JFrame {
   private JPanel Pane;
	
	private static String chemin;
	private static String li;
        private static int a=0;
	private static String cont="  Le contenue de Fichier : : ";
	private static String lex =" L'analyse Lexicale du Fichier : :";
	private static String syn =" L'analyse Syntaxique du Fichier : :";
	private static String sem =" L'analyse Sémantique du Fichier : :";
	private static List<String> lignes;
	private static Vector<String> vec3 =new Vector<String>();
	private static Path path;
	private static String mot="";
	
    /**
     * Creates new form comp
     */
    public comp() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        jFrame1.setSize(new java.awt.Dimension(392, 300));
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(0, 153, 0));
        jButton5.setText("enterer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jFrame1.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 153, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Entrer le chemin de votre fichier");
        jFrame1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 280, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/Search_24x24.png"))); // NOI18N
        jButton1.setText("charger un fichier");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/Archive_256x256.png"))); // NOI18N
        jButton2.setText("Analyse lexicale");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N
        jButton3.setText("Analyse syntaxique");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/ivo.jpg"))); // NOI18N
        jButton4.setText("Analyse sémantique");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Commandes:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setToolTipText("");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Sortie:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public static void lexical(Vector v, Vector v3,int m) {
		String mot="";
		for(int x=0;x<v.size();x++) {
			mot = mot+v.elementAt(x);
		}
		String ligne=" ";
		int j=0;
		char l = (char) v.elementAt(j);
		if(l=='0' || l=='1'|| l=='2'|| l=='3'|| l=='4'|| l=='5'|| l=='6'|| l=='7'|| l=='8'|| l=='9')
		{
                    int v1=0;
			for(int x=1;x<v.size();x++)
			{
				char m2 = (char)v.elementAt(x);
				if(m2=='0' || m2=='1'|| m2=='2'|| m2=='3'|| m2=='4'|| m2=='5'|| m2=='6'|| m2=='7'|| m2=='8'|| m2=='9')
				{v1=v1+0;}
				else {v1=v1+1;}
			}
			if(v1==0) {
				ligne= mot +" ==> nombre entier . ";
			}
			else if(v1>0) {
				ligne= mot +" ==> nombre réel . ";
			}
		}
		else if (l=='"')
		{
			ligne= mot +" ==> mot réservé pour limitation d'une chaine de caractére .";
		}
		else if (l=='S')
			{
			if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);
                        if (l=='t')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);                     
                        if (l=='a')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                      
                        if (l=='r')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                        
                        if (l=='t')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                        
                        if (l=='_')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                        
                        if (l=='P')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                        
                        if (l=='r')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                        
                        if (l=='o')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                        
                        if (l=='g')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                        
                        if (l=='r')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                        
                        if (l=='a')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                        
                        if (l=='m')
                        {
                           ligne= mot +" ==> Mot reservé début d'un programme";
                        }
                        else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                                    }
                        else ligne= mot +" ==> Mot non reconnue . ";
				}
                        else ligne= mot +" ==> Mot non reconnue . ";
				}
			else ligne= mot +" ==> Mot non reconnue . ";
				}
                        else ligne= mot +" ==> Mot non reconnue . ";
				}
                        else ligne= mot +" ==> Mot non reconnue . ";
				}
			else ligne= mot +" ==> Mot non reconnue . ";
				}
                        else ligne= mot +" ==> Mot reservé debut";
				}
                        else ligne= mot +" ==> Mot non reconnue . ";
				}
			else ligne= mot +" ==> Mot non reconnue . ";
				}
                        else ligne= mot +" ==> Mot non reconnue . ";
				}
                        else if (l=='h')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);                     
                        if (l=='o')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                      
                        if (l=='w')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                        
                        if (l=='M')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                        
                        if (l=='e')
                        {
                          if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);  
                        if (l=='s')
                        {
                           ligne= mot +" ==> Mot reservé afficher un message";
                        }
                        else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                                    }
                        else ligne= mot +" ==> Mot non reconnue . ";
				}
                        else ligne= mot +" ==> Mot afficher une valeur ";
				}
			else ligne= mot +" ==> Mot non reconnue . ";
				}
                        else ligne= mot +" ==> Mot non reconnue . ";
				}
                        else ligne= mot +" ==> Mot non reconnue . ";
				}	
                        else if (l=='I')
			{
			if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);
                        if (l=='n')
				{
			if (j<v.size()-1) {j++;}
					 l = (char)v.elementAt(j);
                                
                        if (l=='t')
				{
			if (j<v.size()-1) {j++;}
					 l = (char)v.elementAt(j);
                                
                        if (l=='_')
				{
                           ligne= mot +" ==> Mot reservé déclaration d un entier";
                                }
                        else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                                    }
                        else ligne= mot +" ==> Mot non reconnue . ";
				}
                        else if (l=='f')
                        {
                         ligne= mot +" ==>mot reserve pour une condition";
                        }
                         else
				ligne= mot +" ==> Mot non reconnue . ";
				}	
                        else if (l==':'|l==',')
			{
                             ligne= mot +" ==> caractere reservé";
                        }
                         else if (l=='i'|l=='j')
			{
                             ligne= mot +" ==> identificateur";
                        }
                        else if (l==';')
			{
			if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);
                        if (l==';')
                        {
                          ligne= mot +" ==> Mot reservé";  
                        }
                        else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                        }
                        
                        else if (l=='G')
			{
			if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);
                        if (l=='i')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='v')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='e')
                        {
                         ligne= mot +" ==> Mot reservé ";
                        }
                         else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                        }
                        else ligne= mot +" ==> Mot non reconnue . ";
                        }
                        else ligne= mot +" ==> Mot non reconnue . ";
                        }
                        
                 else if (l=='R')
			{
			if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);
                        if (l=='e')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='a')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='l')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='_')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                           ligne= mot +" ==> Mot reservé declaration d un real ";      
                        }
                        else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                        }
                        else ligne= mot +" ==> Mot non reconnue . ";
                        }
                        else ligne= mot +" ==> Mot non reconnue . ";
                        }
                        else ligne= mot +" ==> Mot non reconnue . ";
                        }        
                else if (l=='-')
                        {
                          ligne= mot +" ==> Mot reservé pour une condition ";      
                        }
                else if (l=='<')
                        {
                          ligne= mot +" ==> symbol inferieur ";      
                        }
                else if (l=='>')
                        {
                          ligne= mot +" ==> symbol superieur ";      
                        }
                 else if (l=='E')
			{
			if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);
                        if (l=='l')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='s')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='e')
                        {
                           ligne= mot +" ==> mot reservé pour une condition";      
                        }
                        else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                        }
                        else ligne= mot +" ==> Mot non reconnue . ";
                        }
                        else if (l=='n')
                        {
                            if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='d')
                        {
                            if (j<v.size()-1) {j++;}
                        
				 l = (char)v.elementAt(j); 
                        if (l=='_')
                        {
                            if (j<v.size()-1) {j++;}
                        
				 l = (char)v.elementAt(j); 
                         if (l=='P')
                        {
                            if (j<v.size()-1) {j++;}
                        
				 l = (char)v.elementAt(j); 
                         if (l=='r')
                        {
                            if (j<v.size()-1) {j++;}
                        
				 l = (char)v.elementAt(j); 
                         if (l=='o')
                        {
                            if (j<v.size()-1) {j++;}
                        
				 l = (char)v.elementAt(j); 
                          if (l=='g')
                        {
                            if (j<v.size()-1) {j++;}
                        
				 l = (char)v.elementAt(j); 
                          if (l=='r')
                        {
                            if (j<v.size()-1) {j++;}
                        
				 l = (char)v.elementAt(j); 
                         if (l=='a')
                        {
                            if (j<v.size()-1) {j++;}
                        
				 l = (char)v.elementAt(j); 
                         if (l=='m')
                        {                 
                         ligne= mot +" ==>mot reserve fin du programme";
                        }
                         else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                        }
                         else ligne= mot +" ==> Mot non reconnue . ";
                        }
                          else ligne= mot +" ==> Mot non reconnue . ";
                        }
                          else ligne= mot +" ==> Mot non reconnue . ";
                        }
                         else ligne= mot +" ==> Mot non reconnue . ";
                        }
                         else ligne= mot +" ==> Mot non reconnue . ";
                        }
                         else ligne= mot +" ==> Mot non reconnue . ";
                        }
                        else ligne= mot +" ==> Mot non reconnue . ";
                        }
                        else ligne= mot +" ==> Mot non reconnue . ";
                        }
                        else ligne= mot +" ==> Mot non reconnue . ";
                        }
                
                         else if (l=='A')
			{
			if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j);
                        if (l=='f')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='f')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='e')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='c')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='t')
                        {
                         ligne= mot +" ==> Mot d affectation";
                        }
                         else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                        }
                        else ligne= mot +" ==> Mot non reconnue . ";
                        }
                        else ligne= mot +" ==> Mot non reconnue . ";
                        }
                        else ligne= mot +" ==>Identificateur  ";
                        }
                        else ligne= mot +" ==> Mot non reconnue . ";
                        }
                       
                         
                        else if (l=='t')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='o')
                        {
                         ligne= mot +" ==>mot d'affectation";
                        }
                         else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                        }
                         
                        
                          else if (l=='/')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        if (l=='/')
                        {
                            if (j<v.size()-1) {j++;}
                        }
				 l = (char)v.elementAt(j); 
                        if (l=='.')
                        {
                         ligne= mot +" ==>mot affiche un commantaire";
                        }
                         else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                        }
                        else if (l=='F')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        if (l=='i')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        if (l=='n')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        if (l=='i')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        if (l=='s')
                        {
                         if (j<v.size()-1) {j++;}
				 l = (char)v.elementAt(j); 
                        
                        if (l=='h')
                        {
                         ligne= mot +" ==> Mot reservé fin";
                        }
                         else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                        }
                        else  ligne= mot +" ==> Mot non reconnue . ";
				}
                        else ligne= mot +" ==> Mot non reconnue . ";
				}
                        else ligne= mot +" ==> Mot non reconnue . ";
				}
                        else ligne= mot +" ==> Mot non reconnue . ";
				}	
                        else
				{
				ligne= mot +" ==> Mot non reconnue . ";
				}
                        
		vec3.addElement(ligne);
	}

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
			
				
			
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           // TODO add your handling code here:
           jFrame1.show();
          
    }//GEN-LAST:event_jButton1ActionPerformed
     
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
           
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3MouseClicked

    public static void syn(Vector v,Vector vec3)
	{        
		String ligne = "";
		for(int i=0;i<v.size();i++)
		{
			ligne =ligne + " " +v.elementAt(i);
		}
                
                
		if(v.elementAt(0).equals("Start_Program")&&(a==0))
		{
                     
			if(v.size()==1) 
			{
				ligne = ligne +" ==> \"public static void main(String[] args) {\";";
			
                        }
			else ligne =ligne +" ==> Erreur Syntaxique .";
		a++;
                }
                
               
               
                
		else if(v.elementAt(0).equals("End_Program"))
		{
                   
			if(v.size()==1) 
			{
                             if(a==1)
                        {
				ligne = ligne +" ==> }";
                                a++;
			}
			else ligne =ligne +" ==> Erreur Syntaxique .";
		}
                        else ligne =ligne +" ==> Erreur Syntaxique .";
                }
                else if(v.elementAt(0).equals("Int_Number"))
		{
			String k =",";
                        String f =";;";
			if(v.elementAt(1).equals(":")) 
			{
                            
				int i=v.size();
                                
					if(v.elementAt(i-1).equals(f)) 
                                        {                                
						 ligne =ligne +" ==> Declaration d un entier.";
					}
					else ligne =ligne +" ==> Erreur Syntaxique .";
				}
				
			else ligne =ligne +" ==> Erreur Syntaxique .";
		}
		else if(v.elementAt(0).equals("ShowMes"))
		{
			String k ="\"";
                        String f =";;";
			if(v.elementAt(1).equals(":")) 
			{
                            
				int i=v.size();
                                
				if(v.elementAt(i-2).equals(k)) 
				{
					if(v.elementAt(i-1).equals(f)) 
                                        {                                
						 ligne =ligne +" ==> Affichage d'un message a l'écran .";
					}
					else ligne =ligne +" ==> Erreur Syntaxique .";
				}
				else ligne =ligne +" ==> Erreur Syntaxique .";
			}
			else ligne =ligne +" ==> Erreur Syntaxique .";
		}
                else if(v.elementAt(0).equals("ShowVal"))
		{
			String k ="\"";
                        String f =";;";
			if(v.elementAt(1).equals(":")) 
			{
                            
				int i=v.size();
                       			if(v.elementAt(i-1).equals(f)) 
                                        {                                
						 ligne =ligne +" ==> Affichage d'une valeur .";
					}
					else ligne =ligne +" ==> Erreur Syntaxique .";			
			}
			else ligne =ligne +" ==> Erreur Syntaxique .";
		}
                else if(v.elementAt(0).equals("Give"))
		{
			String k ="\"";
                        String f =";;";
			
                            if(v.elementAt(2).equals(":")) 
			{
				int i=v.size();
                       			if(v.elementAt(i-1).equals(f)) 
                                        {                                
						 ligne =ligne +" ==> Affectation .";
					}
					else ligne =ligne +" ==> Erreur Syntaxique .";			
			
		}else ligne =ligne +" ==> Erreur Syntaxique .";
                }
                else if(v.elementAt(0).equals("If"))
		{
			String k ="--";
                        String f =";;";
			
                            if(v.elementAt(2).equals(k)) 
			{
				int i=v.size();
                       			if(v.elementAt(i-1).equals(f)) 
                                        {                                
						 ligne =ligne +" ==> Erreur Syntaxique  .";
					}
					else ligne =ligne +" ==>condition Syntaxique .";			
			
		}else ligne =ligne +" ==> condition Syntaxique .";
                }
                else if(v.elementAt(0).equals("Affect"))
		{
			String k ="to";
                        String f =";;";
			
                            if(v.elementAt(2).equals(k)) 
			{
				int i=v.size();
                       			if(v.elementAt(i-1).equals(f)) 
                                        {                                
						 ligne =ligne +" ==> Affectation .";
					}
					else ligne =ligne +" ==> Erreur Syntaxique .";			
			
		}else ligne =ligne +" ==> Erreur Syntaxique .";
                }
		else if(v.elementAt(0).equals("//."))
		{
			ligne = ligne +" ==> commentaire .";
		}
                else if(v.elementAt(0).equals("Start"))
		{
			if(v.size()==1) 
			{
				ligne = ligne +" ==> {";
			}
			else ligne =ligne +" ==> Erreur Syntaxique .";
		}
		
		else if(v.elementAt(0).equals("Finish"))
		{
			if(v.size()==1) 
			{
				ligne = ligne +" ==> }";
			}
			else ligne =ligne +" ==> Erreur Syntaxique .";
		}
		else if(v.elementAt(0).equals("Else"))
		{
			if(v.size()==1) 
			{
				ligne = ligne +" ==> else";
			}
			else ligne =ligne +" ==> Erreur Syntaxique .";
                }
                
		else if(v.elementAt(0).equals("Real_Number"))
		{
			String k =",";
                        String f =";;";
			if(v.elementAt(1).equals(":")) 
			{
                            
				int i=v.size();
                                
					if(v.elementAt(i-1).equals(f)) 
                                        {                                
						 ligne =ligne +" ==> Declaration d un reel.";
					}
					else ligne =ligne +" ==> Erreur Syntaxique .";
				}
				
			else ligne =ligne +" ==> Erreur Syntaxique .";
		}
		else ligne =ligne +" ==> Erreur Syntaxique .";
		
		vec3.addElement(ligne);
	
        }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       try {
				lignes = Files.readAllLines(path);
				vec3= new Vector();
				
				char k=' ';
				for (String ligne : lignes) {
					Vector v= new Vector();
					Vector v1= new Vector();
					for(int i=0;i<ligne.length();i++)
					{
						k=ligne.charAt(i);
						if (k != ' ')
						{
							v1= new Vector();
							mot = mot +k;
						}
						else {
						v1.addElement(k);	
						if (v1.size()==1)
						{
						v.addElement(mot);
						mot="";
						}
						}
					}
					if (k==' ') {v1.addElement(k);}
					if (v1.size()==0)
					{
					v.addElement(mot);
					mot="";
					}
					syn(v,vec3);
				}
				for (int v=0;v<vec3.size();v++) 
				{
					syn=syn + "\n" +vec3.get(v);
				}
				jTextArea1.setText(syn);
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		
	
        
    }//GEN-LAST:event_jButton3ActionPerformed
public static void sema(Vector v,Vector vec3){
        String ligne = "";
		for(int i=0;i<v.size();i++)
		{
			ligne =ligne + " " +v.elementAt(i);
		}
		if(v.elementAt(0).equals("Start_Program"))
		{
			if(v.size()==1) 
			{
				ligne = ligne +" ==> Début du programme .";
			}
			else ligne =ligne +" ==> Erreur Semantique .";
		}
		else if(v.elementAt(0).equals("End_Program"))
		{
			if(v.size()==1) 
			{
				ligne = ligne +" ==> Fin du programme .";
			}
			else ligne =ligne +" ==> Erreur Semantique .";
		}
		else if(v.elementAt(0).equals("ShowMes"))
                {
                         ligne =ligne +" ==> Affichage d'un message a l'écran .";
		}
                else if(v.elementAt(0).equals("ShowVal"))
                {
                     if(v.elementAt(1).equals(":"))
				{
					String mot= (String) v.elementAt(2);
					int j=0,i=0;
                                }
		     ligne =ligne +" ==> Affichage de la valeur";
		}
	
		else if(v.elementAt(0).equals("//."))
		{
			ligne = ligne +" ==> commentaire .";
		}
		else if(v.elementAt(0).equals("Finish"))
		        {
				ligne = ligne +" ==> Fin du block .";
			}
			
		else if(v.elementAt(0).equals("Start"))
		        {
				ligne = ligne +" ==> debut du block .";
			}
			
		else if(v.elementAt(0).equals("Else"))
		{
			if(v.size()==1) 
			{
				ligne = ligne +" ==> sinon .";
			}
			else ligne =ligne +" ==> Erreur Semantique .";
		}
		else if(v.elementAt(0).equals("Else"))
		{
			if(v.size()==1) 
			{
				ligne = ligne +" ==> sinon .";
			}
			else ligne =ligne +" ==> Erreur Semantique .";
		}
                else if(v.elementAt(0).equals("If"))
		{
			String k ="--";
                        String f =";;";
			
                            if(v.elementAt(2).equals(k)) 
			{
				int i=v.size();
                       			if(v.elementAt(i-1).equals(f)) 
                                        {                                
						 ligne =ligne +" ==> Erreur Semantique  .";
					}
					else ligne =ligne +" ==>condition alors action .";			
			
		}else ligne =ligne +" ==> condition alors action .";
                }
                else if(v.elementAt(0).equals("Give"))
		{
			String k ="\"";
                        String f =";;";
			
                            if(v.elementAt(2).equals(":")) 
			{
				int i=v.size();
                       			if(v.elementAt(i-1).equals(f)) 
                                        {                                
						 ligne =ligne +" ==> Affectation .";
					}
					else ligne =ligne +" ==> Erreur Syntaxique .";			
			
		}
                            else ligne =ligne +" ==> Erreur Syntaxique .";
                }
		else if(v.elementAt(0).equals("Affect"))
		{
			String mot = (String) v.elementAt(1);
			String z="";
			char k = ' ';
			boolean error =false;
			Vector v2 =new Vector();
			int vir =0;
			for (int i=0;i<mot.length();i++)
			{
				k=mot.charAt(i);
				v2.addElement(k);
			}
			for (int i=1;i<v2.size();i++)
			{
				if (v2.elementAt(i-1).equals(";;"))
				{
					error = true;
				}
			}
			
			String m = (String) v.elementAt(2);
			int j=0;
			char l = m.charAt(j);
			if(l=='0' || l=='1'|| l=='2'|| l=='3'|| l=='4'|| l=='5'|| l=='6'|| l=='7'|| l=='8'|| l=='9')
			{int v1=0;
				for(int x=1;x<m.length();x++)
				{
					char m2 = m.charAt(x);
					if(m2=='0' || m2=='1'|| m2=='2'|| m2=='3'|| m2=='4'|| m2=='5'|| m2=='6'|| m2=='7'|| m2=='8'|| m2=='9')
					{v1=v1+0;}
					else {v1=v1+1;}
				}
				if(v1==0) {
					m="entiere";
				}
				else if(v1>0) {
					m="réelle";
				}
			}
			if(m=="entiere"||m=="réelle")
			{
				
				if(v.elementAt(3).equals("to")&&error==false)
				{
					if(v.size()==4) 
					{
						ligne = ligne +" ==> Affectation d'une valeur "+m+" à " +v.elementAt(1)+" .";
					}
					else ligne =ligne +" ==> Erreur Semantique .";
				}
				else ligne =ligne +" ==> Erreur Semantique .";
			}
			else ligne =ligne +" ==> Erreur Semantique .";
		}
		else if(v.elementAt(0).equals("Give"))
		{
			String mot = (String) v.elementAt(1);
			String z="";
			char k = ' ';
			boolean error =false;
			Vector v2 =new Vector();
			int vir =0;
			for (int i=0;i<mot.length();i++)
			{
				k=mot.charAt(i);
				v2.addElement(k);
			}
			for (int i=1;i<v2.size();i++)
			{
				if (v2.elementAt(i).equals(','))
				{
					error = true;
				}
			}
			if(v.elementAt(2).equals("Affect"))
			{
				mot = (String) v.elementAt(3);
				z="";
				k = ' ';
				v2 =new Vector();
				vir =0;
				for (int i=0;i<mot.length();i++)
				{
					k=mot.charAt(i);
					v2.addElement(k);
				}
				for (int i=1;i<v2.size();i++)
				{
					if (v2.elementAt(i).equals(','))
					{
						error = true;
					}
				}
				if(v.elementAt(4).equals("to")&&error==false)
				{
					if(v.size()==5) 
					{
						ligne = ligne +" ==> Affectation d'une valeur entre Variable .";
					}
					else ligne =ligne +" ==> Erreur Semantique .";
                                }
                                else ligne =ligne +" ==> Erreur Semantique .";
                        }
			else ligne =ligne +" ==> Erreur Semantique .";
		}
		else if(v.elementAt(0).equals("Real_Number"))
		{
			String k =",";
                        String f =";;";
			if(v.elementAt(1).equals(":")) 
			{
                            
				int i=v.size();
                                
					if(v.elementAt(i-1).equals(f)) 
                                        {                                
						 ligne =ligne +" ==> Condition alors action.";
					}
					else ligne =ligne +" ==> Erreur Semantique .";
				}
				
			else ligne =ligne +" ==> Erreur Semantique .";
		}
                 else if(v.elementAt(0).equals("Int_Number"))
		{
			String k =",";
                        String f =";;";
			if(v.elementAt(1).equals(":")) 
			{
                            
				int i=v.size();
                                
					if(v.elementAt(i-1).equals(f)) 
                                        {                                
						 ligne =ligne +" ==> Declaration des entiers.";
					}
					else ligne =ligne +" ==> Erreur Semantique .";
				}
				
			else ligne =ligne +" ==> Erreur Semantique .";
		}
		
		else ligne =ligne +" ==> Erreur Semantique .";
		
		vec3.addElement(ligne);
	
                }
	
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
				lignes = Files.readAllLines(path);
				vec3= new Vector();
				
				char k=' ';
				for (String ligne : lignes) {
					Vector v= new Vector();
					Vector v1= new Vector();
					for(int i=0;i<ligne.length();i++)
					{
						k=ligne.charAt(i);
						if (k != ' ')
						{
							v1= new Vector();
							mot = mot +k;
						}
						else {
						v1.addElement(k);	
						if (v1.size()==1)
						{
						v.addElement(mot);
						mot="";
						}
						}
					}
					if (k==' ') {v1.addElement(k);}
					if (v1.size()==0)
					{
					v.addElement(mot);
					mot="";
					}
					sema(v,vec3);
				}
				for (int v=0;v<vec3.size();v++) 
				{
					sem=sem + "\n" +vec3.get(v);
				}
				jTextArea1.setText(sem);
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		
                 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        chemin=jTextArea2.getText();
					       path = Paths.get(chemin);
							try {
								lignes = Files.readAllLines(path);
								for (String ligne : lignes) {
									cont = cont + "\n" + ligne;
							    }
								jTextArea1.setText(cont);
							} catch (IOException e1) {
								// TODO Auto-generated catch block
								e1.printStackTrace();
							}
			
		
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
				lignes = Files.readAllLines(path);
				for (String ligne : lignes) {
					int i=0,j=0,f=0,m=0;
					char k = ' ';
					String l;
					Vector vec1 =new Vector();
					Vector vec2 =new Vector();
					while(i<ligne.length()) 
				             {
						k=ligne.charAt(i);
						if(k == '"') {m=1;}
						if(k == '%') {m=m+1;}
						if(k == '.') {m=m+1;}
						if(k == '.') {m=m+1;}
						if(k == ','|| k=='_') {m=m+10;}
						if(k == '>'|| k=='<'||k=='=') {m=100;}
						if(k != ' ') {
							f++;
							j=0;
							vec1.addElement(k);
						}
						else { 
							j++;
							if (j==1&& f!=0)
							{
								vec2=vec1;
								lexical(vec2,vec3,m);
								vec1=new Vector();
							}
						}
					i++;
					}
					if (k==' ') {j++;}
					if (j==1||j==0)
					{
						vec2=vec1;
						lexical(vec2,vec3,m);
						vec1=new Vector();
					}
			    }
				for (int v=0;v<vec3.size();v++) 
				{
					lex=lex + "\n" +vec3.get(v);
				}
				jTextArea1.setText(lex);
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
